#!/bin/sh
#
# @name F250 Maritime Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer adminpc
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.125
param set-default CA_ROTOR0_PY 0.125
param set-default CA_ROTOR0_KM 0.015652892561983472
param set-default CA_ROTOR1_PX -0.125
param set-default CA_ROTOR1_PY -0.125
param set-default CA_ROTOR1_KM 0.015652892561983472
param set-default CA_ROTOR2_PX 0.125
param set-default CA_ROTOR2_PY -0.125
param set-default CA_ROTOR2_KM -0.015652892561983472
param set-default CA_ROTOR3_PX -0.125
param set-default CA_ROTOR3_PY 0.125
param set-default CA_ROTOR3_KM -0.015652892561983472

# Phase 2 F250 baseline keeps conservative Iris motor dynamics while exposing
# F250 naming, rotor geometry, and the maritime external-vision EKF setup.
param set EKF2_EV_CTRL 3
param set EKF2_HGT_REF 3
param set EKF2_GPS_CTRL 0
param set EKF2_BARO_CTRL 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
